version: '2'
services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8000:80'
    networks:
      - krypton
  mariadb:
    image: 'mariadb:10'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'yii2basic'
      MYSQL_USER: 'krypton'
      MYSQL_PASSWORD: '1234'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'kryptonmariadb:/var/lib/mysql'
    networks:
      - krypton
networks:
  krypton:
    driver: bridge
volumes:
  kryptonmariadb:
    driver: local